# ============================================
# 🔹 SERVER CONFIGURATION
# ============================================
server.port=8080
spring.application.name=ExamHub Authentication System

# ============================================
# 🔹 DATABASE (MySQL)
# ============================================
spring.datasource.url=jdbc:mysql://localhost:3306/university_module
spring.datasource.username=root
spring.datasource.password=abc123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
CREATE DATABASE examdb;
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true



# ============================================
# 🔹 JPA / HIBERNATE SETTINGS
# ============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ============================================
# 🔹 FILE UPLOAD DIRECTORY
# ============================================
file.upload-dir=C:\\Users\\Anjali\\OneDrive\\Desktop\\BE_Project\\exam_auth_uploads

# ============================================
# 🔹 GMAIL SMTP FOR OTP
# ============================================
# ================= MAIL CONFIG =================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=siraskar2005@gmail.com
spring.mail.password=qldahsmptxstlugy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000



# ============================================
# 🔹 FAST2SMS CONFIG
# ============================================
fast2sms.api.key=UqamoVIgTQlPJbDcf20jCOGRvMF5XnBWx68usrLZhzitSY1edpDktCgWsoqRj1FXzLJ3Zd8fmHyKGxPh


# ============================================
# 🔹 JWT (Security)
# ============================================
jwt.secret=ReplaceThisSecretKeyForJWTGeneration
jwt.expirationMs=3600000

# ============================================
# 🔹 OTP CONFIGURATION
# ============================================
otp.expiration.minutes=5
