package com.example.examauth.student_exam.model;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

import java.time.LocalDateTime;

/**
 * Final seat allocation for each student per exam per college.
 * Generated by the University Admin once halls are configured.
 *
 * Single source of truth for:
 *   - Roll Number  (unique within exam + college, per UNIQUE constraint)
 *   - Hall name    (denormalized for admit card display)
 *   - Seat number  (format: <hallPrefix>-<3-digit serial>)
 *
 * AdmitCardService reads from this table with a safe fallback
 * when allocation has not yet been generated.
 */
@Entity
@Table(
    name = "exam_seat_allocations",
    uniqueConstraints = {
        // One seat per registration per subject
        @UniqueConstraint(
            name = "uq_seat_per_registration",
            columnNames = {"registration_id", "subject_id"}
        ),
        // Roll number unique within exam + college + subject
        @UniqueConstraint(
            name = "uq_roll_per_exam_college_subject",
            columnNames = {"exam_id", "college_id", "subject_id", "roll_number"}
        )
    },
    indexes = {
        // Core lookup for admit card generation
        @Index(name = "idx_esa_registration_id",  columnList = "registration_id"),
        @Index(name = "idx_esa_exam_id",          columnList = "exam_id"),
        @Index(name = "idx_esa_college_id",       columnList = "college_id"),
        // Composite for supervisor seating chart queries
        @Index(name = "idx_esa_exam_college",     columnList = "exam_id,college_id"),
        // For hall-level views
        @Index(name = "idx_esa_hall_id",          columnList = "hall_id")
    }
)
@Data
@NoArgsConstructor
@AllArgsConstructor
public class ExamSeatAllocation {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // ─────────────────────────────────────────────────────────────────────────
    // FK: Registration → keeps the link to the approval record
    // ─────────────────────────────────────────────────────────────────────────
    /** Plain FK — kept as Long to avoid lazy-load issues in service layer */
    @Column(name = "registration_id", nullable = false)
    private Long registrationId;

    /** FK → users.userId — the student */
    @Column(name = "student_id", nullable = false)
    private Long studentId;

    /** PRN — denormalized for fast display on hall ticket */
    @Column(name = "prn", length = 30)
    private String prn;

    /** Student full name — denormalized for seating chart display */
    @Column(name = "student_name")
    private String studentName;

    // ─────────────────────────────────────────────────────────────────────────
    // FK: Exam + College
    // ─────────────────────────────────────────────────────────────────────────
    @Column(name = "exam_id", nullable = false)
    private Long examId;

    @Column(name = "subject_id")
    private Long subjectId;

    @Column(name = "college_id", nullable = false)
    private Long collegeId;

    /** Denormalized college name for display on seating chart */
    @Column(name = "college_name")
    private String collegeName;

    // ─────────────────────────────────────────────────────────────────────────
    // FK: Hall — @ManyToOne relationship (refinement #4)
    // ─────────────────────────────────────────────────────────────────────────
    /**
     * Full @ManyToOne relationship to ExamHall for join-based queries.
     * FetchType.LAZY prevents N+1 when loading large seating lists.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "hall_id", nullable = false, foreignKey = @ForeignKey(name = "fk_esa_hall"))
    private ExamHall hall;

    /**
     * Denormalized hall name for admit card / seating chart display.
     * Avoids lazy-load issues when the Hall entity is not needed.
     * e.g. "Lecture Hall 101"
     */
    @Column(name = "hall_name")
    private String hallName;

    /**
     * Physical seat identifier.
     * Format: <hallPrefix>-<3-digit serial within hall>
     * e.g. "A-001", "B-025"
     */
    @Column(name = "seat_number", nullable = false, length = 20)
    private String seatNumber;

    /**
     * Official roll number for the exam.
     * Format: <COLLEGE_CODE>/<EXAM_YEAR>/<3-digit serial within college>
     * e.g. "ABC/2026/001"
     * UNIQUE per (exam_id, college_id) — enforced by DB constraint above.
     */
    @Column(name = "roll_number", nullable = false, length = 30)
    private String rollNumber;

    /**
     * Serial order within the college for this exam (1-based).
     * Determines both seat number and roll number ordering.
     * Sorted by PRN alphabetically before generation.
     */
    @Column(name = "serial_in_college")
    private Integer serialInCollege;

    /** When this allocation record was generated */
    @Column(name = "generated_at", updatable = false)
    private LocalDateTime generatedAt;

    @PrePersist
    protected void onCreate() {
        generatedAt = LocalDateTime.now();
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Convenience accessor for queries that only need the hall ID
    // ─────────────────────────────────────────────────────────────────────────
    public Long getHallId() {
        return hall != null ? hall.getId() : null;
    }
}
