# ============================================
# 🔹 SERVER CONFIGURATION
# ============================================
server.port=${PORT:8081}
spring.application.name=ExamHub Authentication System

# ============================================
# 🔹 DATABASE (MySQL)
# ============================================
# 🔹 DATABASE (MySQL)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ============================================
# 🔹 JPA / HIBERNATE SETTINGS
# ============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ============================================
# 🔹 GMAIL SMTP FOR OTP
# ============================================
# ================= MAIL CONFIG =================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=60000
spring.mail.properties.mail.smtp.timeout=60000
spring.mail.properties.mail.smtp.writetimeout=60000


# ============================================
# 🔹 FAST2SMS CONFIG
# ============================================
fast2sms.api.key=${FAST2SMS_API_KEY}


# ============================================
# 🔹 JWT (Security)
# ============================================
jwt.secret=${JWT_SECRET}
jwt.expirationMs=3600000

# ============================================
# 🔹 OTP CONFIGURATION
# ============================================
otp.expiration.minutes=5

# ============================================
# FILE UPLOAD CONFIGURATION (Profile Photos)
# ============================================

# Folder where uploaded profile photos will be stored
# This means inside your backend project:
# backend/uploads/profile/
file.upload-dir=uploads/profile


# Maximum size allowed for single uploaded file
# (Profile photo should not exceed 10MB)
spring.servlet.multipart.max-file-size=10MB


# Maximum total request size (if multiple files uploaded together)
spring.servlet.multipart.max-request-size=10MB
